---
#resource-path: ${user.home}${file.separator}outstagram-resource-test${file.separator}
spring:
  profiles: default
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: testAdmin
    password: testPassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#signing :
#  #sha256(outstagram)
#  key : F79FEA4B2DFB766FE645F05853069FF883271ABD1BCE56C46CEDCA1F9723593C


logging:
  level:
    passionfactory : debug

---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: testAdmin
    password: testPassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#signing :
#  #sha256(outstagram)
#  key : F79FEA4B2DFB766FE645F05853069FF883271ABD1BCE56C46CEDCA1F9723593C


logging:
  level:
    passionfactory : debug