---
resource-path: ${user.home}${file.separator}passion${file.separator}
spring:
  profiles: default
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: testAdmin
    password: testPassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



logging:
  level:
    passionfactory : debug

---
resource-path: ${user.home}${file.separator}passion${file.separator}
spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: testAdmin
    password: testPassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



logging:
  level:
    passionfactory : debug